CC = g++
CFLAGS = -std=c++0x
LIBRARY = /home/draif/Documents/Algorithm/Libraries
INCLUDE = -I$(LIBRARY)
OUT = Electrification

all: $(OUT)

$(OUT): 
	$(CC) Electrification.cpp -o $@ $(CFLAGS) $(INCLUDE)
